### ISSUE TITLE
ServerlessInsight MVP

### ISSUE THREAD

**Issue by Blankll** [geek-fun/serverlessinsight#5]
# Epic ServerlessMVP

## Context
the goal of ServerlessInsight MVP is to ensure that users can use ServerlessInsight to define and deploy an accessible web application consisting of an FC and ApiGateway,  HTTP requests can get simple responses generated from an express  app hosted  FC

## Tasks
- [ ] definition: implement variables
- [ ] definition: implement tags
- [ ] definition: implement stage
- [ ] FC code stored in OSS(not required if a express app not exceeds the limit)
- [ ] implement action: destory

**Comment by Blankll** [comment]
# definition: implement variables
paremeters are defined at top of the schema like:
```yaml
vars:
  region: cn-hangzhou
  account_id: 1234567890
```
